=== victorvisus/LMSGI04_Tarea-XSD/LMGSI04_XSD/public_html/pedidos.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:annotation>

        <xs:documentation xml:lang="es-ES">
            <fecha>14/04/2021</fecha>
            <autor>Víctor Visús García</autor>
            <validacion>https://www.freeformatter.com/xml-validator-xsd.html</validacion>
            
        </xs:documentation>


    </xs:annotation>

    <!-- elemento simple Sección ENVÍO -->
    <xs:element name="responsable" type="texto60" />
    <xs:element name="calle" type="texto60"/>
    <xs:element name="num" type="xs:positiveInteger"/>
    <xs:element name="cp" type="xs:positiveInteger"/>
    <xs:element name="ciudad" type="texto60"/>

    <!-- elemento simple Sección ALBARÁN -->
    <xs:element name="fecha_pedido">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="dia" />
                    <xs:attribute ref="mes" />
                    <xs:attribute ref="anyo" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="tipo" >
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <!-- Puedo o no aparecer el atributo -->
                    <xs:attribute ref="nota"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="revision">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="dias" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <!-- elemento simple Sección ARTÍCULOS -->
    <xs:element name="observaciones" type="texto60"/>



    <!-- atributo etiqueta root -->
    <xs:attribute name="num_pedido" >
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <!-- Indica que primero tiene que ir una letra [A-B] y después 7 dígitos \d{7} -->
                <xs:pattern value="[A-Z]\d{7}" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <!-- atributos Sección ENVÍO -->
    <xs:attribute name="cod_sucursal">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <!-- Indica que primero tiene que ir una letra [A-B] y después 2 dígitos [0-9]{2} -->
                <xs:pattern value="[A-Z][0-9]{2}" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="dpto">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <!-- El atributo dpto solo acepta los valores indicados -->
                <xs:enumeration value="Unica" />
                <xs:enumeration value="Almacen" />
                <xs:enumeration value="Gestion" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <!-- atributos Sección ALBARÁN -->
    <xs:attribute name="dia" type="xs:gDay" />
    <xs:attribute name="mes">
        <xs:simpleType>
            <xs:restriction  base="xs:string">
                <xs:enumeration value="enero" />
                <xs:enumeration value="febrero" />
                <xs:enumeration value="marzo" />
                <xs:enumeration value="abril" />
                <xs:enumeration value="mayo" />
                <xs:enumeration value="junio" />
                <xs:enumeration value="julio" />
                <xs:enumeration value="agosto" />
                <xs:enumeration value="septiembre" />
                <xs:enumeration value="octubre" />
                <xs:enumeration value="noviembre" />
                <xs:enumeration value="diciembre" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="anyo" type="xs:gYear" />

    <xs:attribute name="nota">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="urgente" />
                <xs:enumeration value="incompleto" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="dias">
        <xs:simpleType>
            <xs:restriction base="xs:positiveInteger">
                <xs:maxInclusive value="15" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>




    <!-- tipos de datos definidos por el usuario -->
    <xs:simpleType name="texto60">
        <xs:restriction base="xs:string">
            <xs:maxLength value="60" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="datosDireccion">
        <xs:sequence>
            <xs:element ref="calle" />
            <xs:element ref="num" />
            <xs:element ref="cp" />
            <xs:element ref="ciudad" />
        </xs:sequence>
        <xs:attribute ref="cod_sucursal" use="required" />
        <xs:attribute ref="dpto" use="required" />
    </xs:complexType>


    <!-- elementos complejos -->
    <xs:element name="observaciones_pedido">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tipo" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="albaran">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="fecha_pedido" />
                <xs:element ref="observaciones_pedido" />
                <xs:element ref="revision" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="envio">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="responsable" />
                <xs:element name="direccion" type="datosDireccion" minOccurs="1" maxOccurs="2" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="pedido">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="envio" />
                <xs:element ref="albaran" />
                <!-- <xs:element ref="articulos" /> -->
            </xs:sequence>
            <xs:attribute ref="num_pedido" use="required" />
        </xs:complexType>
    </xs:element>


    <!-- elemento root -->
    <xs:element name="Pedidos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="pedido" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

        


</xs:schema>

=== victorvisus/LMSGI04_Tarea-XSD/LMGSI04_XSD/public_html/pedidoSchema.xml
<?xml version= "1.0" encoding="UTF-8"?>

<Pedidos xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="pedidos.xsd">
    <!-- Hoja de pedido -->
    <pedido num_pedido="B1234567">

        <!-- Datos del envio -->
        <envio>
            <responsable>Federico Grillo</responsable>
            <direccion cod_sucursal="F12" dpto="Ãšnica">
                <calle>la calle de envio</calle>
                <num>3</num>
                <cp>29640</cp>
                <ciudad>Fuenjirola</ciudad>
            </direccion>
        </envio>
    </pedido>
</Pedidos>
